- hosts: fio_clients
  become: yes
  vars:
    nics: []
    result_dir: /root/ntap-sysconfig-output

  tasks:
    - name: Creating directory to collect info about the hosts
      ansible.builtin.file: 
        state: directory
        path: "{{ result_dir }}"

    - name: Gathering general info about the OS
      ansible.builtin.setup:
        gather_subset: all
      register: output_setup
    
    - name: Gathering kernel settings
      ansible.builtin.shell:
        cmd: sysctl -a 
      register: output_sysctl

    - name: Gathering info about NUMA hardware list 
      ansible.builtin.shell:
        cmd: numactl --hardware
      register: output_numactl
    
    - name: Gathering info about network interfaces and their NUMA node domain
      ansible.builtin.shell:
        cmd: "cat /sys/class/net/{{ item }}/device/numa_node"
      loop: "{{ nics }}"
      register: output_nic_numa_node

    - name: Gathering info about network interfaces and their CPU lists
      ansible.builtin.shell:
        cmd: "cat /sys/class/net/{{ item }}/device/local_cpulist"
      loop: "{{ nics }}"
      register: output_nic_local_cpulist

    - name: Gathering info about interrupt handling
      ansible.builtin.shell:
        cmd: "ethtool -l {{ item }}"
      loop: "{{ nics }}"
      register: output_nic_interrupt_handling

    - name: Gathering info about NIC TX and RX queue sizes
      ansible.builtin.shell:
        cmd: "ethtool -g {{ item }}"
      loop: "{{ nics }}"
      register: output_nic_tx_rx_queue_size
    
    - name: Gathering info about MTU size
      ansible.builtin.shell:
        cmd: "ip a | grep {{ item }}"
      loop: "{{ nics }}"
      register: output_nic_mtu_size
    
    - name: Gathering info about PCIe Max Read Request
      ansible.builtin.shell:
        cmd: "setpci -s $(ethtool -i {{ item }} | grep bus-info | awk -F\"o: \" '{ print $2 }') cap_exp+8.w"
      loop: "{{ nics }}"
      register: output_pci_mrrs

    - name: Gathering info about 10bits PCIe tags
      ansible.builtin.shell:
        cmd: "setpci -s $(ethtool -i {{ item }} | grep bus-info | awk -F\"o: \" '{ print $2 }') cap_exp+28.w"
      loop: "{{ nics }}"
      register: output_pci_10b_tags

    - name: Flushing command output to files
      ansible.builtin.copy:
        content: "{{ lookup('vars', item.name ) | to_nice_yaml }}"
        dest: "{{ item.file }}"
      loop: 
        - { name: "output_numactl", file: "{{ result_dir }}/{{ inventory_hostname }}_numactl_hardware.json" }
        - { name: "output_nic_numa_node", file: "{{ result_dir }}/{{ inventory_hostname }}_nic_numa_node.json" }
        - { name: "output_nic_local_cpulist", file: "{{ result_dir }}/{{ inventory_hostname }}_nic_local_cpulist.json" }
        - { name: "output_nic_interrupt_handling", file: "{{ result_dir }}/{{ inventory_hostname }}_nic_interrupt_handling.json" }
        - { name: "output_nic_tx_rx_queue_size", file: "{{ result_dir}}/{{ inventory_hostname }}_nic_tx_rx_queue_size.json" }
        - { name: "output_nic_mtu_size", file: "{{ result_dir }}/{{ inventory_hostname }}_nic_mtu_size.json" }
        - { name: "output_pci_mrrs", file: "{{ result_dir }}/{{ inventory_hostname }}_pcie_mrrs.json" }
        - { name: "output_pci_10b_tags", file: "{{ result_dir }}/{{ inventory_hostname }}_pcie_10b_tags.json"}
        - { name: "output_setup", file: "{{ result_dir }}/{{ inventory_hostname }}_setup.json" }
        - { name: "output_sysctl", file: "{{ result_dir }}/{{ inventory_hostname }}_sysctl.json" }
      delegate_to: localhost
